language: csharp
dist: xenial
mono: none
dotnet: 5.0

branches:
  only:
  - master

services:
  - docker
  - postgresql

addons:
  postgresql: "10"

before_script:
  - psql -c "create database roadkilltests;" -U postgres
  - psql -c "CREATE USER roadkill WITH PASSWORD 'roadkill';" -U postgres
  - psql -c "ALTER USER roadkill WITH SUPERUSER;" -U postgres

# TODO: add version bumping to the assembly
script:
   - dotnet restore
   - dotnet build -c Release
   - pushd src/Roadkill.Tests.Unit
   - dotnet test -c Release --logger:"console;verbosity=detailed"
   - popd
   - pushd src/Roadkill.Tests.Integration
   - dotnet test -c Release --logger:"console;verbosity=detailed"
   - popd
   - pushd src/Roadkill.Api
   - export DOCKER_TAG="3.0.$TRAVIS_BUILD_NUMBER"
   - echo "Using $DOCKER_TAG for the Docker tag"
 #  - dotnet publish -c Release
 #  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 #  - docker build -t "anotherchris/roadkill-api:latest" -t "anotherchris/roadkill-api:$DOCKER_TAG" .
 #  - docker push "anotherchris/roadkill-api:$DOCKER_TAG"
 #  - docker push "anotherchris/roadkill-api:latest"
