steps:
  - id: 'docker-run'
    name: gcr.io/cloud-builders/docker
    args: ['run', '-d', '-p=5432:5432', '--name=roadkill-postgres', '--network=cloudbuild', 'postgres']

  - id: 'sleep'
    name: jwilder/dockerize:0.6.1
    args: ['dockerize', '-timeout=60s', '-wait=tcp://postgres:5432']

  - id: 'psql-create-db'
    name: postgres
    args: ['psql', '--host=postgres', '--user=postgres', '--command', 'CREATE DATABASE roadkill;']
    waitFor: ['sleep']

  - id: 'psql-create-user'
    name: gcr.io/cloud-builders/docker
    args: ['psql', '--host=postgres', '--user=postgres', '--command', 'CREATE USER roadkill WITH PASSWORD ''roadkill'';']
    waitFor: ['psql-create-db']

  - id: 'psql-assign-role'
    name: gcr.io/cloud-builders/docker
    args: ['psql', '--host=postgres', '--user=postgres', '--command', 'ALTER USER roadkill WITH SUPERUSER;']
    waitFor: ['psql-create-user']

  - id: 'dotnet-build'
    name: gcr.io/cloud-builders/dotnet
    args: ['build', '-c', 'Release']

  - id: 'dotnet-test-unit'
    name: gcr.io/cloud-builders/dotnet
    args: ['test']
    dir:  'src/Roadkill.Tests.Unit'
    waitFor: ['dotnet-build']

  - id: 'dotnet-test-integration'
    name: gcr.io/cloud-builders/dotnet
    args: ['test']
    dir:  'src/Roadkill.Tests.Integration'
    waitFor: ['dotnet-build']